language: node_js
node_js:
  - 8
  - node # <-- add this to your .travis.yml for Node.js projects

script:
  - npm test

after_success:
  - npm doc

deploy:
  provider: npm
  email: haouarin@gmail.com
  api_key: $NPM
  on:
    tags: true
    repo: soocrate/soocrate-core
notifications:
  email: false
